language: php

sudo: false

cache:
  directories:
    - $HOME/.composer.cache

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.3

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

before_script:
  - cp .env.example .env
  - php artisan key:generate

script: vendor/bin/phpunit --verbose
